// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3MEt1Gyy1_Lw-zBM1SZDfeIEfAe0n2K4',
    appId: '1:785183110673:web:17251cad1daf399565e3b0',
    messagingSenderId: '785183110673',
    projectId: 'blueberry-b4fff',
    authDomain: 'blueberry-b4fff.firebaseapp.com',
    storageBucket: 'blueberry-b4fff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLdB4y8fL5arelPp3eaUaXE4B6eqYxRVk',
    appId: '1:785183110673:android:ff756e435e44f9d465e3b0',
    messagingSenderId: '785183110673',
    projectId: 'blueberry-b4fff',
    storageBucket: 'blueberry-b4fff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_bixdxGtnTjW2IoNgSy0JnUykdPnOHvQ',
    appId: '1:785183110673:ios:85a1dc5ffe54dec665e3b0',
    messagingSenderId: '785183110673',
    projectId: 'blueberry-b4fff',
    storageBucket: 'blueberry-b4fff.appspot.com',
    iosBundleId: 'com.example.blueberryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_bixdxGtnTjW2IoNgSy0JnUykdPnOHvQ',
    appId: '1:785183110673:ios:85a1dc5ffe54dec665e3b0',
    messagingSenderId: '785183110673',
    projectId: 'blueberry-b4fff',
    storageBucket: 'blueberry-b4fff.appspot.com',
    iosBundleId: 'com.example.blueberryApp',
  );
}
